# Example CI/CD Workflow
# Copy this file to .github/workflows/ci-cd.yml in your repository

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      namespace:
        type: string
        description: Kubernetes namespace
        required: true
        default: production
      environment:
        type: string
        description: Environment name
        required: true
        default: prod
      application:
        type: string
        description: Application name
        required: true

jobs:
  build:
    name: Build Docker Image
    uses: wearevolt/devops-workflows/.github/workflows/build.yml@v1
    with:
      # Required inputs
      namespace: ${{ inputs.namespace || 'production' }}
      environment: ${{ inputs.environment || 'prod' }}
      application: ${{ inputs.application || 'my-app' }}
      working_directory: .  # Path to your Dockerfile
      ecr_repository: my-app  # Your ECR repository name
      
      # Optional inputs (uncomment to customize)
      # docker_file: Dockerfile
      # ecr_registry: '345594573454.dkr.ecr.us-east-1.amazonaws.com'
      # aws_region: us-east-1
      # aws_account_id: '345594573454'
      # github_oidc_role: github-oidc-provider-aws

  deploy:
    name: Deploy to EKS
    needs: build
    uses: wearevolt/devops-workflows/.github/workflows/deployment.yml@v1
    with:
      # Required inputs
      namespace: ${{ inputs.namespace || 'production' }}
      environment: ${{ inputs.environment || 'prod' }}
      application: ${{ inputs.application || 'my-app' }}
      aws_account_id: '123456789012'  # Your AWS account ID
      eks_cluster_name: prod-cluster  # Your EKS cluster name
      working_directory: helm  # Path to your helm directory
      helm_file_path: ./prod  # Path to helmfile relative to working_directory
      ecr_repository: my-app  # Your ECR repository name
      image_tag: ${{ needs.build.outputs.image_tag }}
      
      # Optional inputs (uncomment to customize)
      # ecr_registry: '345594573454.dkr.ecr.us-east-1.amazonaws.com'
      # aws_region: us-east-1
      # github_oidc_role: iam-github-oidc-role
      # kubectl_version: '1.34.1'
      # kubectl_release_date: '2025-09-19'
      # deployment_timeout: '300s'

